/**:
    ros__parameters:

        configuration:
            camera_id: 0
            camera_name: "usb_cam"
            frame_id: "camera_link"
            width : 640
            height : 480
            framerate : 30.0
            flip_mode : 2 # 0=reverse, 2=normal
            camera_calibration_file: "package://ros2_camera/config/usb_calibration.yaml"
            enable_vslam: False

        vslam:
            publish_pointcloud: true
            publish_pose: true
            localize_only: false
            reset_map: false

            # static parameters
            load_map: false
            map_file: map.bin

            pointcloud_frame_id: map
            camera_frame_id: camera
            min_num_kf_in_map: 5

            #ORB parameters
            ORBextractor/nFeatures: 2000
            ORBextractor/scaleFactor: 1.2
            ORBextractor/nLevels: 8
            ORBextractor/iniThFAST: 20
            ORBextractor/minThFAST: 7

            #Camera Parameters
            #Camera frames per second
            camera_fps: 30
            #Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale) 
            camera_rgb_encoding: false